# Generated by Django 4.2.5 on 2023-10-29 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filter_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(blank=True, max_length=20, verbose_name='марка'),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, choices=[('white', 'white'), ('black', 'black'), ('red', 'red'), ('blue', 'blue')], max_length=20, verbose_name='цвет'),
        ),
        migrations.AlterField(
            model_name='car',
            name='cost',
            field=models.IntegerField(blank=True, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(blank=True, verbose_name='год выпуска'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cost', models.IntegerField()),
                ('firma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='filter_app.company')),
            ],
        ),
    ]
