# Generated by Django 4.2.7 on 2023-11-17 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter_app', '0003_course_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='GPA',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AddField(
            model_name='student',
            name='receives_scholarship',
            field=models.BooleanField(default=False),
        ),
    ]
